[build]
  command = "echo \"window.SUPABASE_CONFIG = { url: '${SUPABASE_URL}', key: '${SUPABASE_ANON_KEY}' };\" > assets/js/config.js"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
